### PR TITLE
#13 select and disabled options

### PR DESCRIPTION
**Pull request by opensource21**
This containts Branch #10 and update selenium version. I create a bug report at [selenium](https://code.google.com/p/selenium/issues/detail?id=8563) too, but have no idea when it will be fixed.

### CODE REVIEW

**Comment by opensource21** [comment]
Please wait with merge https://www.w3.org/Bugs/Public/show_bug.cgi?id=28143 shows me that only disable is a real issue.

**Comment by opensource21** [comment]
You can now merge the request. Let me know if you want a cleanup for the history.

**Comment by elisarver** [comment]
I can't merge this because it also merges #10 and #12. Patches must be able to stand alone for me to be able to cleanly reason about them. I do appreciate the changes, but this patch set is massive. If this depends on #10, then wait for that to be merged before re-submitting a cleaner patch without the unrelated features.

**Comment by opensource21** [comment]
Waiting that #10 is merged and will then provide a clean branch.

**Comment by elisarver** [comment]
#10 is merged. Please re-apply your change to select/disabled from a fresh copy of master and re-submit the PR now.

**Comment by opensource21** [comment]
I create #15 which clean code changes only for this issue.

**Pull request closed without merging**
