### PR TITLE
[#5] Cleanup Packagesturcture

### LINKED ISSUE #5: Package dependencies
Hi,
the package dependencies are not very clean. First we have a cycle between the interfaces and the implementation. Furthermore a user must reference an internal package.
Shall we put the widget stuff in one package `org.selophane.elements` and the elementfactory in a package `org.selophane.factory`?

We could then subpackages `elements.base` (contains Element, ElementImpl and ImplementedBy) and `elements.widgets` (Contains conrete widgets).

`org.selophane.factory` could have an `api`(contains Elementfactory) and `internal` package.
Niels

### PR DESCRIPTION
**Pull request by opensource21**
Fix #5 remove all package cycles. Separate the code to widgets, base and factory.

### CODE REVIEW

**Comment by elisarver** [comment]
Please don't include the # character in branch names, it makes bash sad.

**Comment by elisarver** [comment]
The branch #5_packagedependencies had two commits:

1. dependencies changes
2. updating the blog links

Please re-submit without #2

**Comment by opensource21** [comment]
I will try to remove the # in my branches in the future it's in deed a bad decision some one makes in my company and now I adapt it - sorry for this.
About "updating the blog links": I can't find changes for blog-links. Can you comment this directly at the change?

**Comment by elisarver** [comment]
> About "updating the blog links": I can't find changes for blog-links. Can you comment this directly at the change?

Wrong change-list. sorry.

**Comment by elisarver** [comment]
I corrected the double version change issue due to branches being out of sync and merged the PR.

**Pull request closed without merging**
